# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Pages

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - shell: bash
        run: npm run build --if-present -- --base=/${{ github.event.repository.name }}/
      - name: Upload artifact
        # packaging static assets and uploading artifact that can be deployed to GitHub Pages
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # path to static assets that will be packaged and uploaded
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # action expects artifact named `github-pages` to have been created prior to execution
        # this is done automatically using `actions/upload-pages-artifact`
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v1
